BaseDataSourceV2, BaseExpiringDataSource and fix typo
mirego/trikot.datasources pull request #18
Opened 2020-11-08 20:21 UTC by hugolefrancois

## Description
* New BaseDataSourceV2. It's a new version of the current BaseDataSource, completely rewritten to be have more features. This new version doesn't have invalidate(), or clean() methods. I have personally never used them. This is one of the main reason why I have keep the original BaseDataSource. Open to discussion!

* BaseExpiringDataSource, example of one the possible new feature with the new BaseDataSourceV2. BaseExpiringDataSource allow you to put an expiration date on the data in the datasource. This allow the datasource to refresh is data on a call to "read()" even if the flag REFRESH_CACHE is not used.

* ⚠️ BREAKING CHANGE ⚠️ I fixed a typo in the DataSourceRequest interface: cachableId -> cacheableId !

## Motivation and Context
* I needed features that wasn't possible with the current version of BaseDataSource

## How Has This Been Tested?
* Unit tests
* In production in my last project for the past 4 months

## Types of changes
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (the rename of **cachableId**)

2020-11-08 20:22 UTC, hugolefrancois commented on datasources/src/commonMain/kotlin/com/mirego/trikot/datasources/BaseDataSourceV2.kt
> +@Suppress("UNCHECKED_CAST")
This will be removed as soon as my Pr in trikot.streams will be merged

2020-11-08 20:22 UTC, hugolefrancois commented on datasources/src/commonMain/kotlin/com/mirego/trikot/datasources/BaseDataSourceV2.kt
> +fun <T, R> Publisher<T>.safeCombine(publisher: Publisher<R>): Publisher<Pair<T, R>> {
This will be removed as soon as my Pr in trikot.streams will be merged

2020-11-09 12:43 UTC, marclefrancois commented
Just wondering why not add invalidate and clean in this version and simply for a breaking change ?

Aside from that, is your new version functionally equivalent ?

2020-11-09 12:44 UTC, marclefrancois commented
Or put differently, why would I want to use the older version ?

2020-11-09 12:51 UTC, hugolefrancois commented
> Just wondering why not add invalidate and clean in this version and simply remove the old one and manage the breaking change ?
> 
> Aside from that, is your new version functionally equivalent ?

Because I don't understand the purpose of these methods. Invalidate is doing a refresh, if you want to do a refresh, you only have to call read with the param RERESH_CACHE 🤷‍♂️

About clean, its calling delete of the cache data source (if any) but not on the current data source and remove the publisher from the internal map. But what does really do? Someone can still be listening of that publisher, so its will only have effect for the next person that will call a read, he will have a brand new publisher.

I will need to have a chat with THE creator ;)

2020-11-09 12:51 UTC, hugolefrancois commented
> Or put differently, why would I want to use the older version ?

To avoid a big breaking change.

2020-11-09 13:07 UTC, marclefrancois commented
l'll let you guys chat :) But I think we should not have 2 versions of BaseDataSource. We should pay the upgrade price ASAP

2020-11-09 14:20 UTC, npresseault commented
> Because I don't understand the purpose of these methods. Invalidate is doing a refresh, if you want to do a refresh, you only have to call read with the param RERESH_CACHE 🤷‍♂️

I kind of agree here, invalidate which does trigger refresh does not seem that useful. However, there should be a way to invalidate cache without refresh, for instance after logging out to be sure it won't use the cache on subsequent calls.

2020-11-09 14:33 UTC, hugolefrancois commented
> > Because I don't understand the purpose of these methods. Invalidate is doing a refresh, if you want to do a refresh, you only have to call read with the param RERESH_CACHE 🤷‍♂️
> 
> I kind of agree here, invalidate which does trigger refresh does not seem that useful. However, there should be a way to invalidate cache without refresh, for instance after logging out to be sure it won't use the cache on subsequent calls.

I don't think is really possible to invalidate the data of a publisher. I can erase any disk cache or memory cache inside a specific implementation of a data source (aka: delete() ) but there is nothing I can do with the "live" publisher.

To avoid any issues on logout, instead of trying to "clean" my datasources, I'm using the "user id" in the cacheableId of all my data source. With that trick, if you logout and then you login with another user, there is no chance to have the data of the previous user. And if you login back with the first user, you will still have is data in cache :mindblow:

2020-11-10 19:46 UTC, martingagnon commented
The reason why invalidate and clean existed was a logout use case where a datasource was still emitting the logged data.

The approach you suggest (cache busting) is probably a better approach.

Can you list the features of the V2 Datasource ? In. your PR, you don't seems to address the why creating a new datasource,.

2020-11-10 20:02 UTC, martingagnon requested changes
I really think the race condition should be fixed before merging this.

2020-11-10 20:02 UTC, martingagnon commented on datasources/src/commonMain/kotlin/com/mirego/trikot/datasources/BaseDataSourceV2.kt
> +        if (!isReadInProgress(request)) {
In fact, even this has a bug, updating the list could fail... maybe use an AtomicListReference that will assure you that you value is set.

2020-11-10 20:02 UTC, martingagnon commented on datasources/src/commonMain/kotlin/com/mirego/trikot/datasources/BaseDataSourceV2.kt
> +abstract class BaseDataSourceV2<R : DataSourceRequest, T>(private val cacheDataSource: DataSource<R, T>? = null) : DataSource<R, T> {
Can we find a name where it explain why it differenciate with BaseDataSource

Is it only the promises ?

2020-11-10 20:02 UTC, martingagnon commented on datasources/src/commonMain/kotlin/com/mirego/trikot/datasources/BaseDataSourceV2.kt
> +abstract class BaseDataSourceV2<R : DataSourceRequest, T>(private val cacheDataSource: DataSource<R, T>? = null) : DataSource<R, T> {
PromiseAwareDataSource ?

2020-11-11 15:34 UTC, hugolefrancois commented on datasources/src/commonMain/kotlin/com/mirego/trikot/datasources/BaseDataSourceV2.kt
> +        publishers.mergeDataPublisher.first().subscribe(CancellableManager(), onNext = {
Yes, this is a hot datasource. As discussed, it will be renamed BaseHotDataSource

2020-11-11 16:04 UTC, martingagnon approved these changes

2020-11-11 16:08 UTC, merged